server:
    port : 8761
spring:
    application:
        name: service-discovery
    cloud:
        config:
            enabled: false
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        instance:
           hostname: localhost
    server:
        enableSelfPreservation: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka


