spring:
  application:
    name: "loans-service"
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3307/loans-db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8090